Automate server and client setup in multi-client setup.
1. Clone the git repository
2. Setup the environment
3. Create server.toml and client.toml files

diff --git a/scripts/run-multiclient b/scripts/run-multiclient
--- a/scripts/run-multiclient
+++ b/scripts/run-multiclient
@@ -36,8 +36,46 @@ clean() {
 }
 
 display_help() {
-    echo "Usage: $0 {run extname|clean extname}" >&2
+    echo "Usage: $0 {run extname|clean extname |setup flag}" >&2
     exit 1
+}
+
+setup() {
+    # Check for a clients.txt file with client related configuration.
+    if [[ ! -f clients.txt ]]; then
+        echo "Missing clients.txt file in the current directory."
+        exit -1
+    fi
+
+    if [[ ! -f server.txt ]]; then
+        echo "Missing server.txt file in the current directory."
+        exit -1
+    fi
+
+    # Clone the git repository and setup the environment.
+    pssh -h server.txt -t 0 -i "git clone https://github.com/utah-scs/splinter.git" &> /dev/null
+    pssh -h server.txt -t 0 -i "cd splinter; ./scripts/setup.py --$extname;" &> /dev/null
+    pssh -h server.txt -t 0 -i "cd splinter; cat nic_info" > nic_info
+    server_pci=$(awk '/^pci/ { print $2; }' < nic_info)
+    server_mac=$(awk '/^mac/ { print $2; }' < nic_info)
+    rm nic_info
+    echo "Server setup completed"
+
+    # Create server.toml file.
+    pssh -h server.txt -t 0 -i "cd splinter; cp db/server.toml-example db/server.toml; \
+                                 sed -E -i 's/[0-9a-fA-F:]{17}/$server_mac/' db/server.toml; \
+                                 sed -E -i 's/0000:04:00.1/$server_pci/' db/server.toml" &> /dev/null
+    echo "server.toml created"
+
+    # Clone the git repository and setup the environment.
+    pssh -h clients.txt -t 0 -i "git clone https://github.com/utah-scs/splinter.git" &> /dev/null
+    pssh -h clients.txt -t 0 -i "cd splinter; ./scripts/setup.py --$extname;" &> /dev/null
+    echo "Client setup completed"
+
+    # Create client.toml file.
+    pssh -h clients.txt -t 0 -i "cd splinter; \
+                                 echo "server_mac: "$server_mac >> nic_info; \
+                                 ./scripts/create-client-toml" &> /dev/null
 }
 
 if [ $# -ne 2 ]; then
@@ -53,6 +91,9 @@ case "$1" in
         ;;
     clean)
         clean # calling function clean()
+        ;;
+    setup)
+        setup # setup --full
         ;;
     *)
         display_help
